src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Annual_Revenue__c</fullName>
        <description>This field will display sum of budget from all related projects in either "Active" or "Completed" and with an end date within the current calendar year</description>
        <label>Current Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Project_Start_Date__c</fullName>
        <description>This field will display the earliest "Start Date" from the related projects</description>
        <label>First Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Project_End_Date__c</fullName>
        <description>This field will display the latest "End Date" from the related projects</description>
        <label>Last Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Projects__c</fullName>
        <description>This field will display the count of projects associated to the account</description>
        <label>No of Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_hours__c</fullName>
        <description>This field is used to store sla hours</description>
        <label>SLA (hours)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Junction2__c.object
<CustomObject>
    <fields>
        <fullName>AccountProject__c</fullName>
        <formula>CASESAFEID(Account__c)&amp; CASESAFEID(Stakeholder__r.Project__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountProject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Stakeholders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Combination of Account and Stakeholder ID</description>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stakeholder__c</fullName>
        <label>Stakeholder</label>
        <referenceTo>Stakeholder__c</referenceTo>
        <relationshipName>Account_Stakeholders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stakeholder</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Junction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Combination of Account and Project Id</description>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Project</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <description>This field is to capture the budget allocated to the project</description>
        <label>Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Minimum_SLA_hours__c</fullName>
        <label>Minimum SLA (hours)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stakeholder__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Stakeholders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project Owner</fullName>
                </value>
                <value>
                    <fullName>Business Controller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JunctionHandler.cls
public class JunctionHandler {
    
    public static void beforeTrigger(List<Junction__c> lstJuncs) {
        
        for(Junction__c j : lstJuncs) {
            j.External_Id__c = j.Account__c+''+J.Project__c;
        }
    }
    
    public static void commonMethod(List<Junction__c> lstJuncs) {
        
        Set<Id> accIds = NEW Set<Id>();
        Set<Id> proIds = NEW Set<Id>();
        
        for(Junction__c objJunc : lstJuncs) {
            accIds.add(objJunc.Account__c);
            proIds.add(objJunc.Project__c);
        }
        updateAccounts(accIds);
        updateProjects(proIds);
    }
    
    public static void deleteAccountStakeholders(List<Junction__c> lstJuncs) {
        
        List<Junction2__c> lstAccStksToDelete = NEW List<Junction2__c>();
        Set<String> setAccStks = NEW Set<String>();
        
        for(Junction__c objJunc : lstJuncs) {
            String accstkId = objJunc.Account__c+''+objJunc.Project__c;
            setAccStks.add(accstkId);
        }
        lstAccStksToDelete = [SELECT Id FROM Junction2__c WHERE AccountProject__c IN : setAccStks];

        if (!lstAccStksToDelete.isEmpty()) {
            delete lstAccStksToDelete;
        }
    }
    
    public static void updateProjects(Set<Id> proIds) {
        
        List<Project__c> lstPrjsToUpdate = NEW List<Project__c>();
        
        for(Project__c objPrj : [
            SELECT
                Minimum_SLA_hours__c, (
                    SELECT
                        Account__r.SLA_hours__c FROM Project__c.Junctions__r ORDER BY Account__r.SLA_hours__c ASC
                )
            FROM Project__c WHERE Id IN : proIds
        ]) {
            
            if (!objPrj.Junctions__r.isEmpty()) {
                
                objPrj.Minimum_SLA_hours__c = objPrj.Junctions__r[0].Account__r.SLA_hours__c;
                lstPrjsToUpdate.add(objPrj);
            }
            else {
                objPrj.Minimum_SLA_hours__c = NULL;
                lstPrjsToUpdate.add(objPrj);
            }
        }
        
        if (!lstPrjsToUpdate.isEmpty()) {
            ProjectHandler.FLAG = FALSE;
            update lstPrjsToUpdate;
        }
    }
    
    public static void updateAccounts(Set<Id> accIds) {
        
        List<Account> lstAccsToUpdate = NEW List<Account>();
        
        Date minDate;
        Date maxDate;
        
        for(Account objAcc : [
            SELECT
                Active__c, (
                    SELECT
                        Project__r.Status__c, Project__r.Start_Date__c, Project__r.End_Date__c, Project__r.Budget__c
                    FROM Account.Junctions__r ORDER BY Project__r.Start_Date__c
                )
            FROM Account WHERE Id IN : accIds
        ]) {
            
            Set<Id> projectIds = NEW Set<Id>();
            
            Boolean IsActive = FALSE;
            
            Integer count = 0;
            Decimal totalrevenue = 0;
            Decimal currentrevenue = 0;
            
            if (!objAcc.Junctions__r.isEmpty()) {
                
                for(Junction__c objJunc : objAcc.Junctions__r) {
                    
                    projectIds.add(objJunc.Project__c);
                    
                    if (count == 0) {
                    
                        minDate = objJunc.Project__r.Start_Date__c;
                        maxDate = objJunc.Project__r.End_Date__c;
                    }
                    
                    if (maxDate < objJunc.Project__r.End_Date__c) {
                        maxDate = objJunc.Project__r.End_Date__c;
                    }
                    
                    if (objJunc.Project__r.Budget__c == NULL) {
                        objJunc.Project__r.Budget__c = 0;
                    }
                    
                    if (
                        objJunc.Project__r.Status__c.equalsIgnoreCase(System.Label.Active) || 
                        objJunc.Project__r.Status__c.equalsIgnoreCase(System.Label.Completed)
                    ) {
                    
                        totalrevenue += objJunc.Project__r.Budget__c;
                        
                        if (objJunc.Project__r.End_Date__c != NULL) {
                            
                            if (objJunc.Project__r.End_Date__c.year() == Date.TODAY().year()) {
                            
                                currentrevenue += objJunc.Project__r.Budget__c;
                            }
                        }
                        if (objJunc.Project__r.Status__c.equalsIgnoreCase(System.Label.Active)) {
                            IsActive = TRUE;
                        }
                    }
                    count++;
                }
            }
            
            objAcc.Active__c = IsActive;
            objAcc.First_Project_Start_Date__c = minDate;
            objAcc.Last_Project_End_Date__c = maxDate;
            objAcc.AnnualRevenue = totalrevenue;
            objAcc.Current_Annual_Revenue__c = currentrevenue;
            objAcc.No_of_Projects__c = projectIds.size();
            
            lstAccsToUpdate.add(objAcc);
        }
        
        if (!lstAccsToUpdate.isEmpty()) {
            QueueableAccountHandler.FLAG = FALSE;
            update lstAccsToUpdate;
        }
    }
    
    public static void createStakeholders(List<Junction__c> lstJuncs) {
        
        Set<Id> proIds = NEW Set<Id>();
        
        for(Junction__c objJunc : lstJuncs) {
            proIds.add(objJunc.Project__c);
        }
        
        List<Stakeholder__c> lstStks = NEW List<Stakeholder__c>();
        
        for(Project__c pro : [
            SELECT 
                (SELECT Name, Project__c, Email__c, Title__c, Type__c FROM Project__c.Stakeholders__r)
            FROM Project__c WHERE Id IN : proIds
        ]) {
            
            if (!pro.Stakeholders__r.isEmpty()) {
                lstStks.addAll(pro.Stakeholders__r);
            }
        }
        
        if (!lstStks.isEmpty()) {
            StakeholderHandler.commonMethod(lstStks);
        }
    }
}