src/objects/Junction2__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Stakeholders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stakeholder__c</fullName>
        <label>Stakeholder</label>
        <referenceTo>Stakeholder__c</referenceTo>
        <relationshipName>Account_Stakeholders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stakeholder</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Junction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Project</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stakeholder__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Stakeholders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StakeholderHandler.cls
public class StakeholderHandler {
    
    public static void commonMethod(List<Stakeholder__c> lstStks) {
        
        Map<Id, List<Stakeholder__c>> mapPrjStks = NEW Map<Id, List<Stakeholder__c>>();
        Map<Id, List<Junction__c>> mapPrjJuncs = NEW Map<Id, List<Junction__c>>();
        
        for (Stakeholder__c objstk : lstStks) {
            
            if (mapPrjStks.containskey(objstk.Project__c)) {
                mapPrjStks.get(objstk.Project__c).add(objstk);
            }
            else {
                mapPrjStks.put(objstk.Project__c, NEW List<Stakeholder__c>{objstk});
            }
        }
        
        for (Junction__c objJunc : [SELECT Account__c, Project__c FROM Junction__c WHERE Project__c IN : mapPrjStks.keySet()]) {
            
            if (mapPrjJuncs.containsKey(objJunc.Project__c)) {
                mapPrjJuncs.get(objJunc.Project__c).add(objJunc);
            }
            else {
                mapPrjJuncs.put(objJunc.Project__c, NEW List<Junction__c>{objJunc});
            }
        }
        
        Map<Id, Junction2__c> mapAccStks = NEW Map<Id, Junction2__c>();
        List<Junction2__c> lstJunc2s = NEW List<Junction2__c>();
        
        for (Id key : mapPrjStks.keySet()) {
            
            for (Stakeholder__c objStk : mapPrjStks.get(key)) {
                
                if (mapPrjJuncs.containsKey(key)) {
                
                    for(Junction__c objJunc : mapPrjJuncs.get(key)) {
                    
                        Junction2__c obj = NEW Junction2__c();
                        obj.Account__c = objJunc.Account__c;
                        obj.Stakeholder__c = objStk.Id;
                        //mapAccStks.put(obj.Account__c, obj);
                        lstJunc2s.add(obj);
                    }
                }
            }
        }
        
        if (!lstJunc2s.isEmpty()) {
            Database.insert(lstJunc2s, FALSE);
        }
    }
}