src/objects/Junction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Project</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectHandler.cls
public class ProjectHandler {
    
    public static boolean FLAG = TRUE;
    
    public Static void commonMethod(Map<Id, Project__c> mapProjects, Boolean IsDelete) {
        
        List<Junction__c> lstJuncs = NEW List<Junction__c>();
        
        for(Project__c objProj : [
            SELECT Status__c, (SELECT Account__c, Project__c FROM Project__c.Junctions__r) FROM Project__c WHERE Id IN : mapProjects.keySet()
        ]) {
            
            lstJuncs.addAll(objProj.Junctions__r);
        }
        
        if (!lstJuncs.isEmpty()) {
            if (IsDelete) {
                delete lstJuncs;
            }
            else {
                JunctionHandler.commonMethod(lstJuncs);
            }
        }
    }
}